# Generated by Django 5.2.17 on 2026-09-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('career', '경력'), ('education', '학력'), ('activity', '활동')], default='career', max_length=10, verbose_name='구분')),
                ('title', models.CharField(max_length=120, verbose_name='직함 / 과정')),
                ('organization', models.CharField(blank=True, max_length=120, verbose_name='기관')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, help_text="비워 두면 '현재'로 표시됩니다.", null=True, verbose_name='종료일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '경력·학력·활동',
                'verbose_name_plural': '경력·학력·활동',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('headline', models.CharField(max_length=200, verbose_name='한 줄 소개')),
                ('bio', models.TextField(blank=True, verbose_name='소개글')),
                ('philosophy', models.TextField(blank=True, verbose_name='개발 철학')),
                ('vibe_coding_approach', models.TextField(blank=True, help_text='AI와 협업하는 과정, 검증 방법, 강점을 적어 주세요. (소개 페이지 별도 섹션)', verbose_name='바이브코딩 작업 방식')),
                ('photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='프로필 사진')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='슬러그')),
                ('summary', models.CharField(max_length=200, verbose_name='한 줄 설명')),
                ('description', models.TextField(verbose_name='배경 / 문제')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='역할')),
                ('solution', models.TextField(blank=True, verbose_name='해결 방법')),
                ('result', models.TextField(blank=True, verbose_name='결과')),
                ('ai_process', models.TextField(blank=True, help_text='바이브코딩으로 진행한 프로젝트라면 프롬프트 전략, 검증 방법 등을 적어 주세요.', verbose_name='AI 협업 과정')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/thumbs/', verbose_name='썸네일')),
                ('demo_url', models.URLField(blank=True, verbose_name='데모 링크')),
                ('repo_url', models.URLField(blank=True, verbose_name='GitHub 링크')),
                ('is_featured', models.BooleanField(default=False, verbose_name='대표 프로젝트')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='작을수록 먼저 표시됩니다.', verbose_name='정렬')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='기술명')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='프로젝트 필터 주소(?tag=슬러그)에 쓰입니다. 비워 두면 자동 생성됩니다.', max_length=60, unique=True, verbose_name='슬러그')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '표시 안 함'), (1, '1/5'), (2, '2/5'), (3, '3/5'), (4, '4/5'), (5, '5/5')], default=0, verbose_name='숙련도')),
                ('is_core', models.BooleanField(default=False, verbose_name='주력 분야')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬')),
            ],
            options={
                'verbose_name': '기술 분류',
                'verbose_name_plural': '기술 분류',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('subject', models.CharField(max_length=120, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수일')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('is_done', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP 해시')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_hash', 'created_at'], name='contact_ip_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='이름')),
                ('url', models.URLField(verbose_name='주소')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.profile')),
            ],
            options={
                'verbose_name': '외부 링크',
                'verbose_name_plural': '외부 링크',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/shots/', verbose_name='스크린샷')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': '스크린샷',
                'verbose_name_plural': '스크린샷',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.skill', verbose_name='사용 기술'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory', verbose_name='분류'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'order'], name='project_pub_order_idx'),
        ),
    ]
